.gitignore, .travis.yml, Gemfile, LICENSE, README.md, Rakefile, files/pki/clean.sh, files/pki/make.sh, files/pki/template_ca.cnf, files/pki/template_host.cnf, lib/simp/beaker_helpers.rb, simp-beaker-helpers.gemspec
Thus is founded a collection of methods to help Beaker scaffold
acceptance tests for SIMP.
SIMP-426 #comment Created rubygem simp-beaker-helpers
SIMP-427 #close
=> SIMP-427 Create rubygem simp-beaker-helpers

lib/simp/beaker_helpers.rb
Found during testing NFS, the helpers need to hash the certificates
appropriately *after* placing them on the client so that the proper
hashing algorithm is used.
SIMP-918 #comment Fix certificate hashing on clients
Change-Id: I6501eed683659df20f843ea26e99be6b0707578f
=> (SIMP-918) Ensure that certificates are hashed

README.md, lib/simp/beaker_helpers.rb
Documentation is good
SIMP-1013 #close
=> (SIMP-1013) Updated README to include suites

README.md, lib/simp/beaker_helpers.rb
Had a rage coding session due to lack of options and added all yumrepo
options to the nodesets.
SIMP-991 #comment Needed mirrors and added everything
=> (SIMP-991) Add support for all yumrepo options

lib/simp/beaker_helpers.rb, lib/simp/rake/beaker.rb
The last release inadvertently broke the regular runs
SIMP-1167 #comment Found issue during testing
=> (SIMP-1167) Fixed error introduced in last release

lib/simp/beaker_helpers.rb
There was a release that never made it into the Git tree. The small
change has been added here and the release number bumped.
SIMP-2487 #close
=> (SIMP-2487) Update for version missing in Git

.travis.yml, files/puppet-agent-versions.yaml, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
Update puppet-agent version table to include 4.10 versions
SIMP-3324 #close
=> (SIMP-3324) Update puppet-agent table

.travis.yml
The last version did not deploy correctly
=> (SIMP-3324) Update to travis.yml for deployment

.travis.yml
Will add it back when we have time
=> (SIMP-3324) Removed broken travis version compare

lib/simp/beaker_helpers/inspec.rb, lib/simp/beaker_helpers/ssg.rb, lib/simp/beaker_helpers/version.rb
There were several issues with the SSG helpers that have been
identified and corrected so that both the remediation and the checks
now work properly.
=> (SIMP-3324) Corrected issues with the SSG helpers

lib/simp/beaker_helpers/inspec.rb, lib/simp/beaker_helpers/version.rb
* Worked around some issues with the InSpec JSON output
* Optimized copying data between host and docker containers
SIMP-3632 #comment Updated for InSpec changes
=> (SIMP-3632) Update for InSpec Changes

lib/simp/beaker_helpers/inspec.rb, lib/simp/beaker_helpers/version.rb
Introduced an error in the last update with InSpec dependency copying
=> (SIMP-3784) Fix inspec copy

lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
Inadvertently left in a call to @@has_rsync in place
=> (SIMP-3784) Typo Fix

CHANGELOG.md, lib/simp/beaker_helpers/inspec.rb, lib/simp/beaker_helpers/ssg.rb, lib/simp/beaker_helpers/version.rb
* Fix Inspec report processing
* Fix SSG build code
* Allow Inspec validation of SSG Remediations to fail
SIMP-4420 #comment Issues found during PAM testing
=> (SIMP-4420) Fix Inspec and SSG issues

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/inspec.rb, lib/simp/beaker_helpers/ssg.rb, lib/simp/beaker_helpers/version.rb, lib/simp/rake/beaker.rb
* Add required package to SSG builds
* Fix upload and download for docker containers
=> (SIMP-4420) Fixes for Inspec and SSG

CHANGELOG.md, Rakefile, lib/simp/beaker_helpers/version.rb, simp-beaker-helpers.gemspec
A gem was released without a GitHub tag in the project
=> (SIMP-MAINT) Version bump due to release

CHANGELOG.md, lib/simp/beaker_helpers/version.rb, simp-beaker-helpers.gemspec
Discovered internally and externally and need to resolve it ASAP.
=> (SIMP-957) Pin net-telnet to ~> 1.1.1

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/suites/puppet_collections/00_default_spec.rb
Bug fix. Bug encountered with docker, due to a lack of assumed ssh keys.
=> (SIMP-5496) Check for file before chmod

.gitlab-ci.yml, CHANGELOG.md, Gemfile, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/default.yml, spec/acceptance/suites/puppet_collections/nodesets/default.yml, spec/acceptance/suites/windows/00_default_spec.rb, spec/acceptance/suites/windows/metadata.yml, spec/acceptance/suites/windows/nodesets/default.yml, spec/lib/simp/beaker_helpers_spec.rb, spec/spec_helper_acceptance.rb
=> (SIMP-5479) Skip fix_errata_on on windows

lib/simp/beaker_helpers.rb
The previous fix missed the fact that /etc/hosts gets mangled by beaker.
=> (SIMP-6102) Ensure that /etc/hosts is correct

CHANGELOG.md, README.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
* Add the ability to handle registration of Red Hat hosts with the RHN.
SIMP-6942 #close
=> (SIMP-6942) Add support for RHEL

lib/simp/rake/beaker.rb, spec/acceptance/suites/windows/00_default_spec.rb, spec/acceptance/suites/windows/nodesets/win2016.yml, spec/acceptance/suites/windows/nodesets/win2019.yml
* Also added a missing requirement to the Gemfile
* Requires the following PRs to function:
* https://github.com/puppetlabs/beaker-vagrant/pull/26
* https://github.com/puppetlabs/beaker-puppet/pull/129
=> (SIMP-MAINT) Add Windows 2016 and 2019 nodesets

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
* Fix the Windows library loading location.
* No longer attempt to load windows libraries by default unless the system is
actually Windows
=> (SIMP-MAINT) Fix Windows support loading location

CHANGELOG.md, lib/simp/beaker_helpers/ssg.rb
=> [SIMP-7831] Support EL8 in the SSG scans

CHANGELOG.md, lib/simp/beaker_helpers/snapshot.rb, spec/acceptance/suites/snapshot/00_snapshot_test_spec.rb
Vagrant changed the output format at the command line.
=> [SIMP-MAINT] Fix Vagrant snapshot issues

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
SIMP-7829 #comment Fix FIPS mode bug found when debugging auditd tests
=> [SIMP-7829] Fix FIPS mode bug

.travis.yml
[SIMP-8800] #close
[SIMP-8800]: https://simp-project.atlassian.net/browse/SIMP-8800
=> (SIMP-8800) Remove Travis CI tests

.fixtures.yml, .gitlab-ci.yml, CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/suites/default/fixture_modules_spec.rb
* Fixed:
* Ensure that `pfact_on` can handle fact dot notation
* Updated the `.gitlab-ci.yml` with the updated header
=> (SIMP-8839) Allow pfact_on to use dot notation

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/docker.yml, spec/acceptance/suites/default/check_puppet_version_spec.rb, spec/acceptance/suites/default/fixture_modules_spec.rb
* Fixed:
* Allow all methods that can safely take SUT arrays to do so
* Ensure thta pfact_on returns a Hash if appropriate
* Fix container support in copy_to
* Added:
* Explicitly support podman local and remote in copy_to
For full podman support, the following are required:
* puppetlabs/beaker-docker#29
* swipely/docker-api#569
SIMP-9131 #close
SIMP-9129 #close
=> (SIMP-9131) Fix container support

CHANGELOG.md, Gemfile, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/docker.yml
* Ensure that containers use the correct method for copying files
=> (SIMP-MAINT) Fix docker copy

.gitlab-ci.yml, CHANGELOG.md, lib/simp/beaker_helpers/ssg.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/oel.yml, spec/acceptance/suites/ssg/00_default_spec.rb
* Fixed:
* Ensure that the openscap-scanner package is installed during SSG runs
* Changed:
* Added OEL nodeset
SIMP-10204 #comment Fixed OEL SSG support
=> (SIMP-10204) Add openscap-scanner package to SSG

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
* Fixed
* Updated calls to the operating system fact when connecting to RHSM
=> (SIMP-MAINT) Fix OS fact

CHANGELOG.md, lib/simp/beaker_helpers.rb
=> Work around a bug in 'puppet lookup' - PUP-11402

CHANGELOG.md, lib/simp/beaker_helpers/ssg.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/default.yml
* Added python-setuptools to the required package listsI
Closes #177
=> Fix SSG Builds

.gitignore, .gitlab-ci.yml, CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/nodesets/amzn2.yml, spec/spec_helper_acceptance.rb
=> Work around Amazon Linux 2 repository issue

CHANGELOG.md, Gemfile, files/pki/make.sh, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/ssg.rb, lib/simp/rake/beaker.rb, simp-beaker-helpers.gemspec, spec/acceptance/nodesets/amzn2.yml, spec/acceptance/nodesets/default.yml, spec/acceptance/nodesets/oel.yml, spec/acceptance/nodesets/ubuntu.yml, spec/acceptance/suites/windows/00_default_spec.rb, spec/acceptance/suites/windows/nodesets/default.yml, spec/acceptance/suites/windows/nodesets/win2016.yml, spec/acceptance/suites/windows/nodesets/win2019.yml
* Fixed:
* Replaced calls to `sed -c` with something POSIX compliant that should work
on non-RHEL systems
* Added:
* Updated all dependencies to their latest versions where possible and removed
depdendencies on deprecated libraries.
Fixes #165
Fixes #185
=> Remove outdated deps and fix sed

lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
Added explicit EPEL support for:
* AlmaLinux
* Rocky
* Amazon 2
=> Add EPEL support for additional OSs

.github/workflows/add_new_issue_to_triage_project.yml, .github/workflows/tag_deploy_rubygem.yml
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Add GHA action to add new issues to triage project

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
=> (#1) Fix Ruby 3.2 compatibility

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
=> Update /etc/hosts when hostname changes

CHANGELOG.md, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb
=> Update /etc/hosts on all nodes when hostname changes

.gitignore, CHANGELOG.md, Gemfile, lib/simp/beaker_helpers.rb, lib/simp/beaker_helpers/version.rb, spec/acceptance/suites/default/fixture_modules_spec.rb, spec/lib/simp/beaker_helpers_spec.rb
Re-publish the breaking changes in 1.36.0 as 2.0.0.
See #236 for details.
=> Release 2.0.0
