- README.md
- lib/simp/beaker_helpers.rb
SIMP-427 #comment Quick bugfix to bring copy_pki_to in line w/pki:copy
> (SIMP-427) Rename cacert.pem to cacerts.pem

- lib/simp/beaker_helpers.rb
SIMP uses structured facts, therefore stringify_facts must be disabled
on all SUTs.  This patch modifies the `fix_errata_on` method to set the
Puppet config key `stringify_facts` to `false` on all SUTs.
SIMP-492 #close #comment `fix_errata_on(suts)` disables stringify_facts
> (SIMP-492) disable stringify_facts on all SUTs

- README.md
- Rakefile
- lib/simp/beaker_helpers.rb
Before this patch, acceptance tests did not cover FIPS mode.  This
commit adds a new helper method `enable_fips_on(suts)` and calls it
within `fix_errata_on(suts)`.  Testing in FIPS mode is now the default
behavior unless the environment variable `BEAKER_fips` is set to `no`.
SIMP-493 #close #comment Added FIPS mode + env var `BEAKER_fips=no`
SIMP-500 #comment Bumped simp-beaker-helpers gem version to 1.0.3
> (SIMP-493) Add FIPS mode + BEAKER_fips=no

- README.md
- lib/simp/beaker_helpers.rb
Before this commit, the `pki_copy` method would scp a PKI cert tree
into the `sut_pki_dir` directory.  This differs from the behavior of
`pki::copy`, which takes a base path, creates a `pki/` subdirectory
underneath it and copies a PKI cert tree under `pki/`.
Since `pki_copy` is intended to simulate `pki::copy`, it has been
updated to also add a `pki/` directory to the `sut_base_dir` before
copying the PKI cert tree.
SIMP-508 #close #comment Made pki_copy add 'pki/' like pki::copy
> (SIMP-510) Make pki_copy add 'pki/' like pki::copy

- lib/simp/beaker_helpers.rb
This adds a fix to remove the hieradata directory on the remote host
prior to copying in a new one.
This works around an issue in Beaker where it will copy the directory
directly into the existing hieradata directory.
SIMP-482 #comment Work around Beaker bug
> (SIMP-482) Add fix to remove target hieradata

- lib/simp/beaker_helpers.rb
- lib/simp/rake/beaker.rb
- simp-beaker-helpers.gemspec
This adds some Rake helpers for Beaker that allow you to run a specific
nodeset. The available nodeset list is printed if an invalid entry is
made.
SIMP-555 #close
> (SIMP-555) Added a task for specific nodeset run

- README.md
- lib/simp/beaker_helpers.rb
Before this commit, `facter -p` and `puppet apply` did not include
custom facts on masterless SUTs (as they had not been pluginsynced).
This commit introduces the method `pluginsync_on(suts)` to gather all
modules' custom facts and make them available in the default factpath.
SIMP-559 #close #comment Added custom fact sync for masterless SUTs
Change-Id: Ic9643765191037de21a0b26d6f6e2e6807e20a01
> (SIMP-559) Sync custom facts on masterless SUTs

- README.md
- lib/simp/beaker_helpers.rb
Updated the FIPS code to work in full enforcing mode. This includes
setting the keylength and cipher for Puppet as well as the ciphers for
SSH.
Also added a yum clean all to ensure that the tests start with a clean
YUM cache.
SIMP-556 #comment Beaker helpers updates for FIPS
Change-Id: Id072744245184c359c45a24c18662113ebeb309f
> (SIMP-556) Updateds to work with FIPS mode

- .gitignore
- Gemfile
- README.md
- Rakefile
- lib/simp/beaker_helpers.rb
- spec/acceptance/pfacter_spec.rb
- spec/acceptance/pki_tests_spec.rb
This commit provides a new method `pfacter_on(sut,fact_name)` that
queries facts using the SUT's `puppet fact` face.  This has some
advantages over the BEAKER DSL's `facter_on` method:
- It honors the SUT's Puppet conf (e.g.,`factpath`,`stringify_facts`)
- The results (parsed from JSON) preserve facts' data structures
SIMP-569 #comment Bumped simp-beaker-helpers gem version to 1.0.10
SIMP-569 #close #comment Added pfacter_on() method for custom facts
Change-Id: Iaa982a6d9504c9a3ecb2a1b1758209e3761c0491
> (SIMP-569) Add method pfacter_on()

- .travis.yml
- lib/simp/beaker_helpers.rb
- `set_hieradata_on` accepts Strings (Hashes are still accepted)
- `BEAKER_copy_fixtures=no` prevents the module-copying phase of init
- `fix_errata` ensures that default OS host_hash items are present
- This change bumps the gem release version up to 1.0.11
SIMP-650 #close
> (SIMP-650) Ensure host_hash items

- lib/simp/beaker_helpers.rb
- lib/simp/rake/beaker.rb
Added Suite support to the usual Beaker acceptance runs.
Suites should sit under spec/acceptance/suites and have a directory per
suite.
There should be a suite named 'default' which will be executed unless
other items are specified to be run by default in a suite configuration
file.
See the `rake -D beaker:suites` documentation for additional details.
SIMP-835 #close
Change-Id: I5e7c2728208cf6b9bc7d1d4367104c6e39ff97a7
> (SIMP-835) Make Beaker more Suite

- Gemfile
- lib/simp/beaker_helpers.rb
Changing to copying all modules at once shaved two minutes off of a
standard test run with 4 hosts.
SIMP-1131 #comment test optimization side effect
> (SIMP-1131) Optimize module copy to SUTs

- lib/simp/beaker_helpers.rb
- lib/simp/rake/beaker.rb
If a non-default suite was specified, it would not execute without a
setting in the configuration file.
SIMP-1223 #close
> (SIMP-1223) Fix non-default runs

- lib/simp/beaker_helpers.rb
All tests should be able to dig into the regular fixtures path at will.
This allows us to do this without needing to resort to hacks in each
module.
SIMP-1165 #comment Added fixtures_path for performing builds more easily
> (SIMP-1165) Add a fixtures_path method

- lib/simp/beaker_helpers.rb
Presently, we copy in the created CA certificate as cacerts.pem. This
file is expected to be auto-generated by the client and will be ignored
completely by the PKI module making this unsuitable for plugging in on
the fly.
This adds a second cert to the mix that will be properly enabled in the
environment when set as the source in the PKI module.
SIMP-1167 #comment Fix for issue found during testing
> (SIMP-1167) Fix for simp-pki compatibility

- Gemfile
- lib/simp/beaker_helpers.rb
Various Vagrant VMs may not have their interfaces activated by default.
This patch ensures that all interfaces will be made available.
SIMP-2487 #close
> (SIMP-2487) Enable all interfaces on each context

- .travis.yml
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
`bundle` commands were failing on fresh checkouts with errors stemming
from the inclusion of `simp/beaker_helpers.rb` in the .gemspec.
This patch fixes the issue, moving the `Simp::BeakerHelpers::VERSION`
constant into its own file and requiring that from the .gemspec instead.
SIMP-2487 #comment Tacking on bugfix to gemspec
> (SIMP-2487) Factor out `version.rb`

- Gemfile
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
This version of Beaker works with the version of Ruby shipped with
Puppet and it has the fixes for running on EL and SuSE systems
incorporated
SIMP-2998 #close
> (SIMP-2998) Bump to Beaker 3.14+

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Facter was throwing garbage into the logs when we were trying to obtain
the modulepath.
Moved fetching the modulepath into its own method and now call that in
the two places where it is used.
SIMP-3257 #close
> (SIMP-3257) Ignore garbage when getting modulepath

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/ssg.rb
- lib/simp/rake/beaker.rb
This adds preliminary support for both SSG scanning and remediation and
InSpec scanning to Beaker for use in testing various systems and
modules.
The README has not been updated because changes may need to be made
once further integration is made.
SIMP-3156 #comment added support in beaker helpers
> (SIMP-3156) Add SSG and InSpec support to Beaker

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
This is not a full solution to the problem, but this patch speeds up
the module transfer *immensely* and may be enough of a mitigation to
work for now.
SIMP-3139 #comment acceleration of module copy
> (SIMP-3139) Acceleration of module copy

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/ssg.rb
- lib/simp/beaker_helpers/version.rb
'copy_to' picks the best method for transferring files to the remote
system and performs a copy.
Docker systems can be finicky about rsync connections and using the
native docker commands is MUCH faster so this code will try docker if
appropriate, rsync if available, and fall back to scp.
This does not affect calling the legacy methods.
> (SIMP-3784) Added 'copy_to' functionality

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/version.rb
- lib/simp/rake/beaker.rb
The upstream version of the rsync call does not behave in the same
manner as either the docker 'tar' behavior or the built-in 'scp'
behavior.
This fixes our call to rsync to work the same way as the other methods
so that all calls to 'copy_to' can expect consistency in behavior.
SIMP-3831 #close
> (SIMP-3831) Fix copy_to rsync call

- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
The rsync target directory workaround did not properly confine itself
to directories.
> (SIMP-3831) Fix bad logic in copy_to

- README.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
* The 'opts' hash appears to be carried globally between all hosts so
any change to an underlying component will probably cause errors later
down the line
* Also now check to ensure that rsync is installed on the remote sysetm
prior to trying to rsync to the system
> (SIMP-3834) Fix for opts object munging

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Fix the code that sets the path to dracut.
Also added a changelog.
SIMP-3996 #close
> (SIMP-3996) simp-beaker-helpers - Fix BEAKER_fips on CentOS 6

- CHANGELOG.md
- files/pki/make.sh
- files/pki/template_host.cnf
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
k8s requires the IP addresses of the nodes to be in the subjectAltNames
list. This adds that, as well as the hostname to the subjectAltNames
list for completeness.
SIMP-4160 #comment Add IP Addresses to subjectAltNames for testing
> (SIMP-4160) Add IP Addresses to subjectAltNames

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
If you are connecting to a FIPS enabled system from a non-FIPS system,
there is a high probability that a rsync connection will fail. Standard
SCP connections are not affected and core Beaker does not provide a
method to pass full options to the sub commands.
SIMP-4272 #comment fips client issue discovered with beaker during testing
> (SIMP-4272) Do not use rsync on FIPS clients

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Before this commit, `pluginsync_on` only synced facts and used many
expensive `on()` methods that scaled poorly with both modules and hosts.
This patch re-implements the method with a simple puppet manifest.  It
syncs all the assets a normal pluginsync would (including augeas lenses) and
only executes a single `apply_manifest_on` per host.
SIMP-4512 #close
> (SIMP-4512) Improve pluginsync_on

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Since https://tickets.puppetlabs.com/browse/PUP-2868, we receive a
warning if we don't specify the section. This is a problem for puppet
5.5.
These warnings were parsed by ruby and provide incorrect return.
We need to ignore stderr as we still have a problem with
https://tickets.puppetlabs.com/browse/PUP-8566
> Avoid warnings when using puppet config print

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
SIMP-4416 #comment discovered that Dir::Tmpname is removed in Ruby 2.5
> (SIMP-4416) Work around removal of Dir::Tmpname

- .gitlab-ci.yml
- .travis.yml
- CHANGELOG.md
- README.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
* New env var BEAKER_no_fix_interfaces, set to skip the fix that brings
up all vagrant interfaces
* Parallelized actions that are used across all hosts using `block_on`
SIMP-4928 #close
> (SIMP-4928) Parallelize tasks

- CHANGELOG.md
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
Our inspec reporting needs highline but the gem did not require it as a
runtime dependency
> (SIMP-4679) Fix dependency on highline

- CHANGELOG.md
- lib/simp/beaker_helpers/ssg.rb
- simp-beaker-helpers.gemspec
The 'master' branch started failing to build so the SSG code was updated
to use the latest tag instead by default
> (SIMP-MAINT) Use the latest SSG tag

- CHANGELOG.md
- README.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Issues with Beaker are causing all parallel activities to fail so they
are being forcibly disabled until we can figure out what's going on.
SIMP-4989 #comment disable parallelization
> (SIMP-4989) Remove parallelization

- CHANGELOG.md
- files/puppet-agent-versions.yaml
- lib/simp/beaker_helpers/version.rb
Update puppet-to-puppet-agent table to include version of puppet-agent
currently slated for SIMP-6.2.0
SIMP-5043 #comment simp-beaker-helpers update
> (SIMP-5043) Update table with puppet-agent 1.10.14

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/ssg.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/suites/default/set_hieradata_on_spec.rb
- spec/acceptance/suites/default/write_hieradata_to_spec.rb
* Change InSpec to use the 'reporter' option instead of 'format'
* Update the SSG to point to the new ComplianceAsCode repository
* Deprecate the 'terminus' parameter in 'write_hieradata_to' and 'set_hieradata_on'
* Add 'copy_hiera_data_to' method to replace the one from beaker-hiera
* Add 'hiera_datadir' method to replace the one from beaker-hiera
This should be a seamless working update for existing SIMP modules
> (SIMP-MAINT) Deprecation Updates

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
Added to fix_errata_on method
SIMP-5429 #comment Cloned keys in fix_errata_on so the same fix doesn't need to
be in every test that applies the ssh puppet module.
> (SIMP-5429) Copy ssh keys to /etc/ssh/local_keys

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
This has been causing issues on locked down system tests and the
potential performance hit is worth having tests that "just work"
> (SIMP-MAINT) Fall back to SSH if rsync doesn't work

- CHANGELOG.md
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/version.rb
The data structure for the host_hash docker-related items that came out
of beaker-docker changed from a full Hash to disparate items so we need
to account for that change.
> (SIMP-MAINT) Add workaround for beaker-docker

- CHANGELOG.md
- lib/simp/beaker_helpers/ssg.rb
Add a workaround for building the SSG content so that the STIG can be
run on CentOS again.
SIMP-6097 #close
> (SIMP-6097) Fix running STIG on CentOS

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
Given the nature of our tests, all hosts should have an FQDN. Since this
only happens once, tests can reset to a short hostname if it is truly
necessary.
SIMP-6102 #close
> (SIMP-6102) Ensure that SUTs have a FQDN

- lib/simp/beaker_helpers.rb
- simp-beaker-helpers.gemspec
Fix another instance related to the host_hash docker related items change as in #90 
Also, remove runtime rubocop dependency as nothing in the code seems to require it.
> Fix beaker-docker support

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/suites/default/install_simp_deps_repo_spec.rb
- added a function, install_simp_repos, that sets up the 
simp  internet repos.  Using this through out
tests will allow it to be updated in one place  should it ever change.
- add parameter that takes a list of names of simp repos to disable.
SIMP-6212  #comment  This fix is needed for pkg-r10k tests
> (SIMP-6212) Add function to install simp deps repo

- lib/simp/beaker_helpers/inspec.rb
- need to support version logic if we want 3.9.0 and newer compatibility
- assumes 'newest' release install
> add license accept to the default run command.

- .gitlab-ci.yml
- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/suites/default/check_puppet_version_spec.rb
- spec/lib/simp/beaker_helpers_spec.rb
This is an emergency fix to handle the rearrangement of the upstream
puppet repositories.
The default version is now pinned to the latest Puppet 5
> (SIMP-MAINT) Bump default version to Puppet 5

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
Added RPM-GPG-KEY-SIMP-6 to the SIMP dependencies repo created
by install_simp_repo().
> (SIMP-MAINT) Add missing GPG key to SIMP deps repo

- .rspec
- lib/simp/beaker_helpers/constants.rb
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/ssg.rb
- spec/acceptance/suites/offline/00_default_spec.rb
- spec/acceptance/suites/offline/README
- spec/acceptance/suites/offline/nodesets/default.yml
Added an offline beaker suite that does the following:
* Starts a libvirt-based VM
* Installs VirtualBox
* Adds a regular user
* Installs RVM for that user
* Clones the simp-at project
* Runs 'rake beaker:suites' inside the simp-at project using
VirtualBox
NOTE: This **MUST** be run on libvirt with nested virtualization enabled
This test should stay disabled by default
SIMP-6815 #comment Add test for offline beaker
> (SIMP-6815) Add offline beaker suite

- CHANGELOG.md
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
* Bump the version of Highline to 2.0+ due to bugs in the latest 1.X series
> (SIMP-MAINT) Bump HighLine version

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
* Added an `is_windows?(sut)` function
* Work around issues with calling `sut.puppet` on Windows SUTs
* Update `copy_fixture_modules_to` to support Windows (slow copy)
* Add Windows support to `puppet_modulepath_on`
SIMP-6916 #comment Update simp-beaker-helpers to support Windows
> (SIMP-6916) Add Windows client support to the beaker helpers functions

- CHANGELOG.md
- README.md
- lib/simp/beaker_helpers/inspec.rb
- lib/simp/beaker_helpers/version.rb
The inspec report processor was not processing all sub-controls for a
given test. In the past, this was due to the in-flux nature of the
inspec reports themselves. The latest releases of inspec seem to have
stabilized and can now be easily, and completely processed.
SIMP-6708 #comment fix simp-beaker-helpers bug discovered during testing
> (SIMP-6708) Fix inspec report processing

- CHANGELOG.md
- lib/simp/beaker_helpers/ssg.rb
- lib/simp/beaker_helpers/version.rb
* Allow users to perform exclusion filters on SSG results
* Allow users to pass Arrays of items to match for SSG results
This was created by the need to filter out broken checks without wanting
to write custom XML processing in each test.
> (SIMP-MAINT) Add flexibility to SSG result matches

- CHANGELOG.md
- Rakefile
- lib/simp/beaker_helpers/version.rb
- lib/simp/rake/beaker.rb
Hide puppet-only tasks when not working on a puppet module to make the
usage less confusing to other usages.
SIMP-7224 #close
> (SIMP-7224) Optionally hide puppet-only tasks

- .fixtures.yml
- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
- spec/acceptance/suites/windows/00_default_spec.rb
- spec/acceptance/suites/windows/nodesets/default.yml
* Update Windows support
* Add require beaker-windows and note installation of gem if missing
* Add geotrust global CA certificate in fix_eratta_on
* Added convenience helper methods
* Add puppet_environment_path_on
* Add file_content_on which is multi-platform safe unlike the built-in
file_contents_on
* Add hiera_config_path_on
* Add get_hiera_config_on
* Add set_hiera_config_on
> (SIMP-MAINT) Windows and convenience updates

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- lib/simp/beaker_helpers/windows.rb
- simp-beaker-helpers.gemspec
The previous location for loading the Windows libraries would not work
in a `:before` block. This moves it into its own module space.
> (SIMP-MAINT) Fix Windows library loading

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
* Allow Vagrant to connect to EL8+ hosts in FIPS mode
[SIMP-7816] #close
[SIMP-7816]: https://simp-project.atlassian.net/browse/SIMP-7816
> (SIMP-7816) Work around Vagrant + EL8 FIPS issue

- CHANGELOG.md
- Gemfile
- lib/simp/beaker_helpers/version.rb
Added support for an environment variable BEAKER_VERSION due to the
Beaker maintenance team being willing to run our tests if they can
easily point to a different location/version for upstream beaker.
> [SIMP-MAINT] Allow different versions of beaker

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/suites/default/install_simp_deps_repo_spec.rb
* Fixed:
* rsync handling has a better check to see if rsync actually works prior to
using it.  The old method had the potential to try and use rsync even if it
no longer worked (FIPS flipped for example).
* Changed:
* Migrated from PackageCloud to the SIMP download server for updates moving
forward.
SIMP-8416 #comment simp-beaker-helpers update
> (SIMP-8416) Packagecloud and rsync fixes

- .fips_fixtures
- CHANGELOG.md
- Gemfile
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/constants.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/nodesets/default.yml
- spec/acceptance/suites/default/check_puppet_version_spec.rb
- spec/lib/simp/beaker_helpers_spec.rb
* Fixed:
* Bumped the core puppet version to 6.X
* Fixed the file_content_on method
* Removed EL 6 support from the tests since the core repos are defunct
* Started removing some of the puppet 4 tests
> (SIMP-MAINT) Various bugfixes

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
This avoids problems with JSON parsing when there is output on stderr.
SIMP-8925 #close
> (SIMP-8925) Use stdout instead of output in pfact_on

- .gitignore
- .gitlab-ci.yml
- CHANGELOG.md
- Rakefile
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/suites/default/fixture_modules_spec.rb
- spec/lib/simp/beaker_helpers_spec.rb
* Fixed:
* Only return a default empty string when `pfact_on` finds a `nil` value
* Added an acceptance test to validate this
* Ensure that we start with `facter -p` for `facter` < 4.0 and continue to
`puppet facts` otherwise
* Updated the Rakefile to skip symlinks in chmods which fixes the ability to
build gems
> Additional pfact_on fixes

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/constants.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/ubuntu.yml
* Added:
* A `enable_epel_on` function that follows the instructions on the EPEL
website to properly enable EPEL on hosts. May be disabled using
`BEAKER_enable_epel=no`.
* An Ubuntu nodeset to make sure our default settings don't destroy other
Linux systems.
SIMP-7822 #comment added EPEL installer for consistency
> (SIMP-7822) Add EPEL installer

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
* Added:
* update_package_from_centos_stream method
* install_latest_package_on method
* Fixed:
* Removed some of the extraneous calls to facter
* Automatically pull the CentOS 8 kernel to the latest version in
CentOS-Stream to work around issues on FIPS systems
[SIMP-9114] #comment Update beaker helpers to work around FIPS issue
[SIMP-9114]: https://simp-project.atlassian.net/browse/SIMP-9114
> (SIMP-9114) Mitigate FIPS issues in CentOS 8.3

- CHANGELOG.md
- lib/simp/beaker_helpers/version.rb
* Fixed version mismatch.  1.21.1 was tagged with an incorrect version
in version.rb.
> (SIMP-MAINT) Bump version for mismatched version

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
* Fixed:
* Reverted the use of OpenStruct due to issues with seralization
* Hash objects have a 'dig' method as of Ruby 2.3 so pinned this gem to a
minimum version of Ruby 2.3
> (SIMP-MAINT) Remove use of OpenStruct

- .fips_fixtures
- CHANGELOG.md
- README.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- lib/simp/rake/beaker.rb
- spec/acceptance/suites/default/install_simp_deps_repo_spec.rb
- spec/acceptance/suites/fips_from_fixtures/00_default_spec.rb
* Fixed:
* Ensure that the simp-crypto_policy module is installed when flipping to FIPS
mode
* Only attempt to install the simp repos once in case they are broken for some
reason
* Added:
* Documentation for all of the beaker environment variables
* set_simp_repo_release() for setting the release and release_type of the
public SIMP yum repos
* set_yum_opts_on() method for setting bulk yum config options
* set_yum_opt_on() method for setting singular yum config options
* install_package_unless_present_on() method
* Allow users to set repos to disable using an environment variable
* A total run time summary for beaker suites
[SIMP-9148] #close
[SIMP-9148]: https://simp-project.atlassian.net/browse/SIMP-9148
> (SIMP-9148) Allow users to set SIMP repo release

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- Test for OEL are failing because nothing is done when epel repo
is enable on OracleLinux.
- OEL has  an oracle-epel-release-<version> rpm.   This fix adds installing
this repo when enable_epel is called in an acceptence test running on
OEL.
SIMP-8932 #comment This fix is needed for the OEL acceptance tests in pupmod-simp-ssh
> (SIMP-8932) Enable EPEL for OEL

- .github/workflows.local.json
- .github/workflows/tag_deploy_rubygem.yml
This patch fixes some problems with GitHub Actions release workflows:
* Individual RubyGems can read `.github/workflows.local.json` to override
build/release commands
* Forked repos's GHA workflows no longer attempt to release when
SemVer-compatible tags are pushed
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9426] #close
[SIMP-9399] #comment rubygem tag fixes in rubygem-simp-beaker-helpers
[SIMP-9407] #close #comment customized release w/`workflows.local.json`
[SIMP-9426]: https://simp-project.atlassian.net/browse/SIMP-9426
[SIMP-9399]: https://simp-project.atlassian.net/browse/SIMP-9399
[SIMP-9407]: https://simp-project.atlassian.net/browse/SIMP-9407
> (SIMP-9399) GLCI & GHA release workflow fixes

- CHANGELOG.md
- simp-beaker-helpers.gemspec
* For `podman` support:
* Bumped the required beaker-docker to between 0.8.3 and 2.0.0
* Added a dependency on docker-api between 2.1.0 and 3.0.0
> (SIMP-MAINT) Podman support

- .gitlab-ci.yml
- CHANGELOG.md
- lib/simp/beaker_helpers/version.rb
- lib/simp/rake/beaker.rb
- Fail an acceptance test when an explicitly-specified nodeset for an
acceptance test suite does not exist and the suite is configured
to fail fast (default behavior).
- Added an acceptance test job in the .gitlab-ci.yml to test this
in lieu of a separate acceptance test using a build user with a
fully-configured rvm environment.
> (SIMP-MAINT) Fail suite when invalid specified nodeset

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/ssg.rb
- lib/simp/beaker_helpers/version.rb
- spec/acceptance/nodesets/default.yml
* Fixed:
* Removed the Streams kernel update for EL 8.3 since it now causes issues
* Use `pfact_on` to select the interface facts to fix Puppet 7 issues
SIMP-10043 #comment Fix fact issues for Puppet 7
> (SIMP-10043) Fix fact and kernel issues

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_cleanup.yml
- .github/workflows/tag_deploy_rubygem.yml
- .gitlab-ci.yml
GitHub actions' Ubuntu 16.04 environment will be removed on Sept 20,
2021.  This patch migrates all workflow using the `ubuntu-16.04`
environment to `ubuntu-latest`.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may apply other updates to ensure conformity.
[SIMP-10541] #close
[SIMP-10450] #comment Add `release_rpms` to rubygem-simp-beaker-helpers
[SIMP-10541]: https://simp-project.atlassian.net/browse/SIMP-10541
[SIMP-10450]: https://simp-project.atlassian.net/browse/SIMP-10450
> (SIMP-10450) GHA: Update ubuntu-16.04 to latest

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
Prevent `spec/` directory symlink recursion
Before this patch, the `tar` operation in `copy_fixture_modules_to`
could get stuck on an endless recursive directory loop when the
`spec/fixtures/modules/` directory contained a symlink to the module
itself.
The `spec/` directory is only used for spec testing and is not
required by SUTs to compile the module's code and data.
This patch prevents tar from recursing module fixtures entirely by
adding `spec/` to the directories that `tar` excludes.
Fixes #173
> Prevent `spec/` directory symlink recursion

- .github/workflows/tag_deploy_rubygem.yml
Added:
- Re-added rubygem release output vars (needed to publish releases to
rubygems.org) to `tag_deploy_rubygem` workflow
> Fix GHA rubygem release workflow

- lib/simp/rake/beaker.rb
- spec/acceptance/nodesets/default.yml
In most modules, we wish to test multiple default nodes but generally
are are not doing multi-node testing.
Instead of using convoluted generators or additional abstract
configuration files, this allows you to simply add `sequential: true` to
the `CONFIG:` section and each host will be broken out into its own
nodeset on the fly and executed.
A future extension of this may allow for tagged clusters to run as
multi-node tests without needing additional files or settings.
> Allow for sequential nodesets

- CHANGELOG.md
- lib/simp/beaker_helpers/version.rb
- lib/simp/rake/beaker.rb
- spec/acceptance/nodesets/amzn2.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/docker.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/nodesets/ubuntu.yml
- spec/acceptance/suites/default/fixture_modules_spec.rb
- spec/acceptance/suites/default/pki_tests_spec.rb
* Fixed:
* Ensure that `multi_node` is enabled by default for backwards compatibility
* Sort the discovered nodesets by default when running with `ALL` nodesets
> Multi_node Fix

- files/pki/make.sh
By definition, the CN of a request is a max of 64 bytes. Google internal hostnames can be longer than 64 bytes, which breaks the cert request generation
Fixes #193
> Limit the length of the CN in the template to 64 characters

- lib/simp/beaker_helpers.rb
Warn the user if the BEAKER_RHSM_USER/PASS aren't set, but allow them to continue. This should support pay-as-you-go cloud services.
> (#195) Allow not registrating subscription-manager

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_cleanup.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/tag_deploy_rubygem.yml
This patch updates GHA workflows to use GCP as a hypervisor when
BEAKER_HYPERVISOR is `google`
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Add GCP support to GLCI

- .github/workflows/pr_acceptance.yml
- .github/workflows/pr_tests.yml
- .rspec
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
- simp-beaker-helpers.gemspec
* Update dependencies in `Gemfile` and `simp-beaker-helpers.gemspec`
* Bump version
* Cleanup affected files for rubocop
* Various fixes for test failures
> Update gem dependencies

- CHANGELOG.md
- lib/simp/beaker_helpers.rb
- lib/simp/beaker_helpers/version.rb
> Fix error when no domain is set
